### ISSUE TITLE
Wrong entity id's

### ISSUE THREAD

**Issue by bshor** [votesmart/political-id-match#3]
I am seeing a lot of errors on the Follow the Money entity id's in this data. For example, Rick C. Beck from AR (votesmart id 150224) is assigned eid of 37971378. But his [FTM page](https://www.followthemoney.org/entity-details?eid=22027748) clearly indicates an entity id of 22027748.

I have a list of about ~1500 suspected errors like this. I'm wondering the best way to fix this.

**Comment by wrm5b** [comment]
Thanks for flagging! This is a result of the process that FTM uses to associate an old system of EIDs and their current system. As we understand it, FTM makes associations between old EIDs and their current EIDs in order to keep the data linked to both. This allows a request using either EID to pull the right data. 

For example, using EID 37971378 redirects to the same FTM page as 22027748. The same is true using FTM's API, which is why the data on our site for Rick Beck is accurate.

I suspect the remainder of your errors are in this same camp. Note that new candidates will not have this "issue" since we never collected their old EIDs.
